/*
 * Grounded Model Exchange (GroMEt) schema for Function Networks
 * This document defines the GroMEt Function Network data model. Note that Metadata is defined in separate spec.  __Using Swagger to Generate Class Structure__  To automatically generate Python or Java models corresponding to this document, you can use [swagger-codegen](https://swagger.io/tools/swagger-codegen/). This can be used to generate the client code based off of this spec, and in the process this will generate the data model class structure.  1. Install via the method described for your operating system    [here](https://github.com/swagger-api/swagger-codegen#Prerequisites).    Make sure to install a version after 3.0 that will support openapi 3. 2. Run swagger-codegen with the options in the example below.    The URL references where the yaml for this documentation is stored on    github. Make sure to replace CURRENT_VERSION with the correct version.    (The current version is `0.1.4`.)    To generate Java classes rather, change the `-l python` to `-l java`.    Change the value to the `-o` option to the desired output location.    ```    swagger-codegen generate -l python -o ./client -i https://raw.githubusercontent.com/ml4ai/automates-v2/master/docs/source/gromet_FN_v{CURRENT_VERSION}.yaml    ``` 3. Once it executes, the client code will be generated at your specified    location.    For python, the classes will be located in    `$OUTPUT_PATH/swagger_client/models/`.    For java, they will be located in    `$OUTPUT_PATH/src/main/java/io/swagger/client/model/`  If generating GroMEt schema data model classes in SKEMA (AutoMATES), then afer generating the above, follow the instructions here: ``` <automates>/automates/model_assembly/gromet/model/README.md ``` 
 *
 * OpenAPI spec version: 0.1.4
 * Contact: claytonm@arizona.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Generic base class for any GroMEt object
 */
@Schema(description = "Generic base class for any GroMEt object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-09T15:16:12.519-07:00[America/Phoenix]")

public class GrometObject {
  @SerializedName("metadata")
  private Integer metadata = null;

  @SerializedName("gromet_object_type")
  private String grometObjectType = null;

  public GrometObject() {
    this.grometObjectType = this.getClass().getSimpleName();
  }
  public GrometObject metadata(Integer metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Index (integer) into the metadata_collection table in GrometFNModule.
   * @return metadata
  **/
  @Schema(description = "Index (integer) into the metadata_collection table in GrometFNModule.")
  public Integer getMetadata() {
    return metadata;
  }

  public void setMetadata(Integer metadata) {
    this.metadata = metadata;
  }

  public GrometObject grometObjectType(String grometObjectType) {
    this.grometObjectType = grometObjectType;
    return this;
  }

   /**
   * Get grometObjectType
   * @return grometObjectType
  **/
  @Schema(description = "")
  public String getGrometObjectType() {
    return grometObjectType;
  }

  public void setGrometObjectType(String grometObjectType) {
    this.grometObjectType = grometObjectType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrometObject grometObject = (GrometObject) o;
    return Objects.equals(this.metadata, grometObject.metadata) &&
        Objects.equals(this.grometObjectType, grometObject.grometObjectType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, grometObjectType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrometObject {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    grometObjectType: ").append(toIndentedString(grometObjectType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
