/*
 * Grounded Model Exchange (GroMEt) schema for Function Networks
 * This document defines the GroMEt Function Network data model. Note that Metadata is defined in separate spec.  __Using Swagger to Generate Class Structure__  To automatically generate Python or Java models corresponding to this document, you can use [swagger-codegen](https://swagger.io/tools/swagger-codegen/). This can be used to generate the client code based off of this spec, and in the process this will generate the data model class structure.  1. Install via the method described for your operating system    [here](https://github.com/swagger-api/swagger-codegen#Prerequisites).    Make sure to install a version after 3.0 that will support openapi 3. 2. Run swagger-codegen with the options in the example below.    The URL references where the yaml for this documentation is stored on    github. Make sure to replace CURRENT_VERSION with the correct version.    (The current version is `0.1.4`.)    To generate Java classes rather, change the `-l python` to `-l java`.    Change the value to the `-o` option to the desired output location.    ```    swagger-codegen generate -l python -o ./client -i https://raw.githubusercontent.com/ml4ai/automates-v2/master/docs/source/gromet_FN_v{CURRENT_VERSION}.yaml    ``` 3. Once it executes, the client code will be generated at your specified    location.    For python, the classes will be located in    `$OUTPUT_PATH/swagger_client/models/`.    For java, they will be located in    `$OUTPUT_PATH/src/main/java/io/swagger/client/model/`  If generating GroMEt schema data model classes in SKEMA (AutoMATES), then afer generating the above, follow the instructions here: ``` <automates>/automates/model_assembly/gromet/model/README.md ``` 
 *
 * OpenAPI spec version: 0.1.4
 * Contact: claytonm@arizona.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GrometFN;
import io.swagger.client.model.GrometObject;
import io.swagger.client.model.Metadata;
import io.swagger.client.model.TypedValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * A GroMEt FN Module. (A Module corresonds to a namespace.) When derived from a source program, the FN is typically decomposed into a hierarchical structure of FNs, with a root GrometFN (that has a Module Outer Box) that will be assigned to the &#x60;fn&#x60; attribute of the GrometFNModule, and then has an array of &#x60;attributes&#x60; that are either themselves GrometFNs (the represent the types, functions, and variable-bound values, defined within the module) or imported elements. 
 */
@Schema(description = "A GroMEt FN Module. (A Module corresonds to a namespace.) When derived from a source program, the FN is typically decomposed into a hierarchical structure of FNs, with a root GrometFN (that has a Module Outer Box) that will be assigned to the `fn` attribute of the GrometFNModule, and then has an array of `attributes` that are either themselves GrometFNs (the represent the types, functions, and variable-bound values, defined within the module) or imported elements. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-02T01:18:52.196-07:00[America/Phoenix]")
public class GrometFNModule extends GrometObject {
  @SerializedName("schema")
  private String schema = "FN";

  @SerializedName("schema_version")
  private String schemaVersion = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("fn")
  private GrometFN fn = null;

  @SerializedName("attributes")
  private List<TypedValue> attributes = null;

  @SerializedName("metadata_collection")
  private List<List<Metadata>> metadataCollection = null;

  public GrometFNModule schema(String schema) {
    this.schema = schema;
    return this;
  }

   /**
   * Get schema
   * @return schema
  **/
  @Schema(description = "")
  public String getSchema() {
    return schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public GrometFNModule schemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  @Schema(description = "")
  public String getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
  }

  public GrometFNModule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the Function Network Module. 
   * @return name
  **/
  @Schema(description = "The name of the Function Network Module. ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GrometFNModule fn(GrometFN fn) {
    this.fn = fn;
    return this;
  }

   /**
   * Get fn
   * @return fn
  **/
  @Schema(description = "")
  public GrometFN getFn() {
    return fn;
  }

  public void setFn(GrometFN fn) {
    this.fn = fn;
  }

  public GrometFNModule attributes(List<TypedValue> attributes) {
    this.attributes = attributes;
    return this;
  }

  public GrometFNModule addAttributesItem(TypedValue attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<TypedValue>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * (sum-type) Array of TypedValues. Currently expect:&lt;br&gt; (1) other GrometFN (type &#x3D; \&quot;FN\&quot;)&lt;br&gt; (2) references to ImportReference (type &#x3D; \&quot;IMPORT\&quot;) 
   * @return attributes
  **/
  @Schema(description = "(sum-type) Array of TypedValues. Currently expect:<br> (1) other GrometFN (type = \"FN\")<br> (2) references to ImportReference (type = \"IMPORT\") ")
  public List<TypedValue> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<TypedValue> attributes) {
    this.attributes = attributes;
  }

  public GrometFNModule metadataCollection(List<List<Metadata>> metadataCollection) {
    this.metadataCollection = metadataCollection;
    return this;
  }

  public GrometFNModule addMetadataCollectionItem(List<Metadata> metadataCollectionItem) {
    if (this.metadataCollection == null) {
      this.metadataCollection = new ArrayList<List<Metadata>>();
    }
    this.metadataCollection.add(metadataCollectionItem);
    return this;
  }

   /**
   * Table (array) of lists (arrays) of metadata, where each list in the Table-array represents the collection of metadata associated with a GroMEt object. 
   * @return metadataCollection
  **/
  @Schema(description = "Table (array) of lists (arrays) of metadata, where each list in the Table-array represents the collection of metadata associated with a GroMEt object. ")
  public List<List<Metadata>> getMetadataCollection() {
    return metadataCollection;
  }

  public void setMetadataCollection(List<List<Metadata>> metadataCollection) {
    this.metadataCollection = metadataCollection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrometFNModule grometFNModule = (GrometFNModule) o;
    return Objects.equals(this.schema, grometFNModule.schema) &&
        Objects.equals(this.schemaVersion, grometFNModule.schemaVersion) &&
        Objects.equals(this.name, grometFNModule.name) &&
        Objects.equals(this.fn, grometFNModule.fn) &&
        Objects.equals(this.attributes, grometFNModule.attributes) &&
        Objects.equals(this.metadataCollection, grometFNModule.metadataCollection) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schema, schemaVersion, name, fn, attributes, metadataCollection, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrometFNModule {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fn: ").append(toIndentedString(fn)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    metadataCollection: ").append(toIndentedString(metadataCollection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
