/*
 * GroMEt Metadata spec
 * Grounded Model Exchange (GroMEt) Metadata schema specification  __Using Swagger to Generate Class Structure__  To automatically generate Python or Java models corresponding to this document, you can use [swagger-codegen](https://swagger.io/tools/swagger-codegen/). We can use this to generate client code based off of this spec that will also generate the class structure.  1. Install via the method described for your operating system    [here](https://github.com/swagger-api/swagger-codegen#Prerequisites).    Make sure to install a version after 3.0 that will support openapi 3. 2. Run swagger-codegen with the options in the example below.    The URL references where the yaml for this documentation is stored on    github. Make sure to replace CURRENT_VERSION with the correct version.    (The current version is `0.1.4`.)    To generate Java classes rather, change the `-l python` to `-l java`.    Change the value to the `-o` option to the desired output location.    ```    swagger-codegen generate -l python -o ./client -i https://raw.githubusercontent.com/ml4ai/automates-v2/master/docs/source/gromet_metadata_v{CURRENT_VERSION}.yaml    ``` 3. Once it executes, the client code will be generated at your specified    location.    For python, the classes will be located in    `$OUTPUT_PATH/swagger_client/models/`.    For java, they will be located in    `$OUTPUT_PATH/src/main/java/io/swagger/client/model/`  If generating GroMEt Metadata schema data model classes in SKEMA (AutoMATES), then afer generating the above, follow the instructions here: ``` <automates>/automates/model_assembly/gromet/metadata/README.md ``` 
 *
 * OpenAPI spec version: 0.1.4
 * Contact: claytonm@email.arizona.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Metadata;
import io.swagger.client.model.Provenance;
import io.swagger.client.model.TextExtraction;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Definition of host derived from a text source. 
 */
@Schema(description = "Definition of host derived from a text source. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-09T12:36:06.656-07:00[America/Phoenix]")
public class TextDefinition extends Metadata {
  @SerializedName("metadata_type")
  private String metadataType = "text_definition";

  @SerializedName("text_extraction")
  private TextExtraction textExtraction = null;

  @SerializedName("variable_identifier")
  private String variableIdentifier = null;

  @SerializedName("variable_definition")
  private String variableDefinition = null;

  public TextDefinition metadataType(String metadataType) {
    this.metadataType = metadataType;
    return this;
  }

   /**
   * Get metadataType
   * @return metadataType
  **/
  @Schema(description = "")
  public String getMetadataType() {
    return metadataType;
  }

  public void setMetadataType(String metadataType) {
    this.metadataType = metadataType;
  }

  public TextDefinition textExtraction(TextExtraction textExtraction) {
    this.textExtraction = textExtraction;
    return this;
  }

   /**
   * Get textExtraction
   * @return textExtraction
  **/
  @Schema(description = "")
  public TextExtraction getTextExtraction() {
    return textExtraction;
  }

  public void setTextExtraction(TextExtraction textExtraction) {
    this.textExtraction = textExtraction;
  }

  public TextDefinition variableIdentifier(String variableIdentifier) {
    this.variableIdentifier = variableIdentifier;
    return this;
  }

   /**
   * Variable identifier
   * @return variableIdentifier
  **/
  @Schema(description = "Variable identifier")
  public String getVariableIdentifier() {
    return variableIdentifier;
  }

  public void setVariableIdentifier(String variableIdentifier) {
    this.variableIdentifier = variableIdentifier;
  }

  public TextDefinition variableDefinition(String variableDefinition) {
    this.variableDefinition = variableDefinition;
    return this;
  }

   /**
   * Variable definition text
   * @return variableDefinition
  **/
  @Schema(description = "Variable definition text")
  public String getVariableDefinition() {
    return variableDefinition;
  }

  public void setVariableDefinition(String variableDefinition) {
    this.variableDefinition = variableDefinition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextDefinition textDefinition = (TextDefinition) o;
    return Objects.equals(this.metadataType, textDefinition.metadataType) &&
        Objects.equals(this.textExtraction, textDefinition.textExtraction) &&
        Objects.equals(this.variableIdentifier, textDefinition.variableIdentifier) &&
        Objects.equals(this.variableDefinition, textDefinition.variableDefinition) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadataType, textExtraction, variableIdentifier, variableDefinition, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextDefinition {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    metadataType: ").append(toIndentedString(metadataType)).append("\n");
    sb.append("    textExtraction: ").append(toIndentedString(textExtraction)).append("\n");
    sb.append("    variableIdentifier: ").append(toIndentedString(variableIdentifier)).append("\n");
    sb.append("    variableDefinition: ").append(toIndentedString(variableDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
